import { type Property, type Testimonial } from './supabase';

export const DEMO_PROPERTIES: Property[] = [
  {
    id: 'demo-1',
    title: 'Penthouse at Burj Khalifa District',
    description: 'An extraordinary penthouse offering panoramic views of the Dubai Fountain and the iconic Burj Khalifa. This residence features floor-to-ceiling windows, a private terrace, and bespoke interior finishes by internationally renowned designers.',
    price: 15000000,
    price_display: 'AED 15,000,000',
    location: 'Downtown Dubai',
    bedrooms: 4,
    bathrooms: 5,
    area: 6500,
    area_unit: 'sqft',
    property_type: 'Penthouse',
    status: 'available',
    featured: true,
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=85'],
    amenities: ['Private Terrace', 'Smart Home System', 'Concierge', 'Valet Parking', 'Private Pool', 'Home Theatre'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    title: 'Waterfront Villa, Palm Jumeirah',
    description: 'An exclusive beachfront villa with direct private beach access, an infinity pool overlooking the Arabian Gulf, and six generously proportioned bedrooms. Every detail has been considered for a life of absolute luxury.',
    price: 45000000,
    price_display: 'AED 45,000,000',
    location: 'Palm Jumeirah',
    bedrooms: 6,
    bathrooms: 7,
    area: 12000,
    area_unit: 'sqft',
    property_type: 'Villa',
    status: 'available',
    featured: true,
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=85'],
    amenities: ['Private Beach', 'Infinity Pool', 'Home Theater', 'Wine Cellar', 'Gym', 'Staff Quarters'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    title: 'Sky Suite, Dubai Marina',
    description: 'A spectacular full-floor apartment delivering 360° views of Dubai Marina and the shimmering Arabian Gulf. Three bedrooms, four bathrooms, and an expansive wraparound terrace make this a truly iconic residence.',
    price: 8500000,
    price_display: 'AED 8,500,000',
    location: 'Dubai Marina',
    bedrooms: 3,
    bathrooms: 4,
    area: 4200,
    area_unit: 'sqft',
    property_type: 'Apartment',
    status: 'under-offer',
    featured: true,
    images: ['https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=1200&q=85'],
    amenities: ['Marina View', 'Private Gym', 'Rooftop Terrace', 'Concierge', 'Covered Parking'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    title: 'Emirates Hills Estate',
    description: 'A palatial estate set within Dubai\'s most prestigious gated community. Overlooking the Montgomerie Golf Course, this seven-bedroom mansion offers unmatched privacy, sprawling gardens, and resort-style amenities.',
    price: 75000000,
    price_display: 'AED 75,000,000',
    location: 'Emirates Hills',
    bedrooms: 7,
    bathrooms: 8,
    area: 18000,
    area_unit: 'sqft',
    property_type: 'Villa',
    status: 'available',
    featured: false,
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=85'],
    amenities: ['Golf Course View', 'Tennis Court', 'Swimming Pool', 'Guest House', 'Landscaped Gardens'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-5',
    title: 'DIFC Luxury Apartment',
    description: 'A sophisticated two-bedroom apartment in the heart of Dubai\'s financial district. Clean lines, premium finishes, and breathtaking city views make this the ideal pied-à-terre for the discerning professional.',
    price: 5500000,
    price_display: 'AED 5,500,000',
    location: 'DIFC',
    bedrooms: 2,
    bathrooms: 3,
    area: 2800,
    area_unit: 'sqft',
    property_type: 'Apartment',
    status: 'available',
    featured: false,
    images: ['https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200&q=85'],
    amenities: ['City Views', 'Concierge', 'Rooftop Pool', 'Gym', 'Covered Parking'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-6',
    title: 'Jumeirah Bay Island Villa',
    description: 'One of Dubai\'s most coveted addresses on the exclusive Jumeirah Bay Island. This signature villa features an architectural masterpiece with five bedrooms, a private jetty, and uninterrupted sea views.',
    price: 95000000,
    price_display: 'AED 95,000,000',
    location: 'Jumeirah Bay Island',
    bedrooms: 5,
    bathrooms: 6,
    area: 15000,
    area_unit: 'sqft',
    property_type: 'Villa',
    status: 'available',
    featured: false,
    images: ['https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&q=85'],
    amenities: ['Private Jetty', 'Sea Views', 'Infinity Pool', 'Smart Home', 'Private Beach'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_TESTIMONIALS: Testimonial[] = [
  {
    id: 'dt-1',
    client_name: 'James & Sarah Mitchell',
    client_title: 'Purchased: Palm Jumeirah Villa',
    client_photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    content: "Taz made our dream of owning a Palm Jumeirah villa an absolute reality. His knowledge of the Dubai market is unrivalled and his negotiation skills saved us millions. We couldn't be happier with our new home.",
    rating: 5,
    property_type: 'Villa',
    visible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'dt-2',
    client_name: 'Ahmed Al-Rashid',
    client_title: 'Investment Portfolio — Downtown Dubai',
    client_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    content: "As an investor, I've worked with many agents in Dubai, but Taz stands out. His market intelligence and off-plan access gave me a significant edge. Three properties later, I trust no one else with my portfolio.",
    rating: 5,
    property_type: 'Investment',
    visible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'dt-3',
    client_name: 'Alexandra Beaumont',
    client_title: 'Sold: DIFC Penthouse',
    client_photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    content: "Taz sold my penthouse above asking price in under two weeks. His marketing strategy and buyer network are exceptional. The entire process was seamless and professional from start to finish.",
    rating: 5,
    property_type: 'Penthouse',
    visible: true,
    created_at: new Date().toISOString(),
  },
];
